databases:
  - name: mysite
    databaseName: rails_app_no3_db
    user: rails_app_no3_db_user

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: ENV['DATABASE_URL']
        fromDatabase:
          name: mysite
          property: connectionString
      - key: ENV['RAILS_MASTER_KEY']
        sync: false