version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      MYSITE_DATABASE_USERNAME: ${MYSITE_DATABASE_USERNAME}
      MYSITE_DATABASE_PASSWORD: ${MYSITE_DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      MYSITE_DATABASE_USERNAME: ${MYSITE_DATABASE_USERNAME}
      MYSITE_DATABASE_PASSWORD: ${MYSITE_DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db
volumes:
  postgres_volume: