version: '3'
databases:
  - name: mysite
    databaseName: rails_app_no3_db
    user: rails_app_no3_db_user

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      MYSITE_DATABASE_USERNAME: ${MYSITE_DATABASE_USERNAME}
      MYSITE_DATABASE_PASSWORD: ${MYSITE_DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/app
    ports:
      - "3000:3000"