version: '3'
databases:
  - name: mysite
    databaseName: rails_app_no3_db
    user: rails_app_no3_db_user

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      DATABASE_URL: "postgresql://rails_app_no3_db_user:password@mysite/rails_app_no3_db"
      RAILS_MASTER_KEY: "8464052bdd36b3fd284e28ad09d197ad"
    volumes:
      - .:/app
    ports:
      - "3000:3000"