default: &default
  adapter: postgresql
  encoding: unicode
  ports: <%= ENV['POSTGRES_PORT'] %>
  pool: 5

development:
  <<: *default
  database: myapp_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db



test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: myapp_production
  username: <%= ENV['MYSITE_DATABASE_USERNAME'] %>
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYSITE_HOST_NAME'] %>

