default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  ports:
      - "3000:3000"
  pool: 5

development:
  <<: *default
  database: myapp_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>



test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: myapp_production
  username: <%= ENV['MYSITE_DATABASE_USERNAME'] %>
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  adapter: postgresql
